ktor:
  deployment:
    port: 80
  application:
    modules:
      - com.example.AppConfigKt.configureHttp
      - com.example.AppConfigKt.configureSerialization
      - com.example.AppConfigKt.configureRouting
