ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.HttpKt.configureHttp
      - com.example.SerializationKt.configureSerialization
      - com.example.RoutingKt.configureRouting
